{{- if and .Values.rbac.create .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "velero-manager.clusterRoleBindingName" . }}
  labels:
    {{- include "velero-manager.labels" . | nindent 4 }}
  {{- with .Values.rbac.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "velero-manager.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "velero-manager.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}