{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "velero-manager.clusterRoleName" . }}
  labels:
    {{- include "velero-manager.labels" . | nindent 4 }}
  {{- with .Values.rbac.clusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  # Core namespace and resource discovery permissions
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  
  # Core resource permissions for discovery and backup operations
  - apiGroups: [""]
    resources: 
      - "pods"
      - "services" 
      - "configmaps"
      - "secrets"
      - "persistentvolumes"
      - "persistentvolumeclaims"
      - "serviceaccounts"
      - "events"
    verbs: ["get", "list", "watch"]
  
  # Apps resources
  - apiGroups: ["apps"]
    resources:
      - "deployments"
      - "replicasets"
      - "statefulsets"
      - "daemonsets"
    verbs: ["get", "list", "watch"]
  
  # Batch resources  
  - apiGroups: ["batch"]
    resources:
      - "jobs"
      - "cronjobs"
    verbs: ["get", "list", "watch"]
  
  # Networking resources
  - apiGroups: ["networking.k8s.io"]
    resources:
      - "ingresses"
      - "networkpolicies"
    verbs: ["get", "list", "watch"]
  
  # Storage resources
  - apiGroups: ["storage.k8s.io"]
    resources:
      - "storageclasses"
      - "volumeattachments"
    verbs: ["get", "list", "watch"]
  
  # RBAC resources for permission checking and discovery
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - "roles"
      - "rolebindings"
      - "clusterroles"
      - "clusterrolebindings"
    verbs: ["get", "list", "watch"]
  
  # Authorization API for RBAC checking (SelfSubjectAccessReview)
  - apiGroups: ["authorization.k8s.io"]
    resources:
      - "selfsubjectaccessreviews"
      - "subjectaccessreviews"
    verbs: ["create"]
  
  # Custom Resource Definitions discovery
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - "customresourcedefinitions"
    verbs: ["get", "list", "watch"]
  
  # Velero-specific resources
  - apiGroups: ["velero.io"]
    resources:
      - "backups"
      - "backupstoragelocations"
      - "deletebackuprequests"
      - "downloadrequests"
      - "podvolumebackups"
      - "podvolumerestores"
      - "resticrepositories"
      - "restores"
      - "schedules"
      - "serverstatusrequests"
      - "volumesnapshotlocations"
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  # Volume snapshot resources (if using CSI snapshots)
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources:
      - "volumesnapshots"
      - "volumesnapshotcontents"
      - "volumesnapshotclasses"
    verbs: ["get", "list", "watch"]
  
  {{- if .Values.rbac.clusterRole.extraRules }}
  # Additional custom rules
  {{- toYaml .Values.rbac.clusterRole.extraRules | nindent 2 }}
  {{- end }}
{{- end }}